// <auto-generated />
using System;
using AppServicios.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppServicios.Api.Migrations
{
    [DbContext(typeof(AppServiciosDbContext))]
    [Migration("20260707010146_SeedInitialServiceCatalog")]
    partial class SeedInitialServiceCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppServicios.Api.Domain.AuditoriaEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Fecha", "Tipo");

                    b.ToTable("AuditoriaEventos");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaOtorgamiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalificacionPromedioProfesionales")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GastoPorMes")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecibeNotificaciones")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalServiciosContratados")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.IpBloqueada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("DesbloqueadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDesbloqueo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ip")
                        .IsUnique();

                    b.ToTable("IpsBloqueadas");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.MensajeSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemitenteNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitudTrabajoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SolicitudTrabajoId", "FechaEnvio");

                    b.ToTable("MensajesSolicitud");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SolicitudTrabajoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.PagoProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaExterna")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("PagosProfesionales");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTrabajoLejano")
                        .HasColumnType("boolean");

                    b.Property<int>("AñosExperiencia")
                        .HasColumnType("integer");

                    b.Property<decimal>("BonoPorDistancia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GananciaMensualActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GananciaMensualObjetivo")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("RadioAlcanceKm")
                        .HasColumnType("integer");

                    b.Property<decimal>("TarifaBase")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTrabajos")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rubros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Servicios eléctricos",
                            Icono = "electricidad",
                            Nombre = "Electricidad"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Servicios de plomería",
                            Icono = "plomeria",
                            Nombre = "Plomería"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Niñeras y cuidadores",
                            Icono = "cuidados-ninos",
                            Nombre = "Cuidados de Niños"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Cuidados de salud",
                            Icono = "enfermeria",
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Reparación de vehículos",
                            Icono = "mecanica",
                            Nombre = "Mecánica"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Trabajo en metal",
                            Icono = "metalurgia",
                            Nombre = "Metalurgia"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Servicios de soldadura",
                            Icono = "soldadura",
                            Nombre = "Soldadura"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Reparaciones técnicas",
                            Icono = "tecnica",
                            Nombre = "Técnica"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Software, soporte IT, redes y servicios digitales",
                            Icono = "tecnologia-sistemas",
                            Nombre = "Tecnología y Sistemas"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Atención clínica, cuidados y asistencia sanitaria",
                            Icono = "salud-enfermeria",
                            Nombre = "Salud y Enfermería"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Descripcion = "Procesos productivos, planta y operación técnica",
                            Icono = "produccion-manufactura",
                            Nombre = "Producción, Manufactura y Operarios"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Descripcion = "Ventas, reparto, logística y atención comercial",
                            Icono = "comercio-logistica",
                            Nombre = "Comercio Ventas y Logística"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Descripcion = "Gestión administrativa, contable y financiera",
                            Icono = "administracion-finanzas",
                            Nombre = "Administración Contabilidad y Finanzas"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Descripcion = "Hotelería, turismo, cocina y atención gastronómica",
                            Icono = "hosteleria-gastronomia",
                            Nombre = "Hostelería Turismo y Gastronomía"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Descripcion = "Obra, mantenimiento general y servicios técnicos",
                            Icono = "construccion-servicios",
                            Nombre = "Construcción y Servicios Generales"
                        });
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("numeric");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Instalaciones, ampliaciones y mejoras eléctricas para viviendas.",
                            Nombre = "Instalación eléctrica domiciliaria",
                            PrecioSugerido = 35000m,
                            RubroId = 1,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Diagnóstico y reparación de fallas eléctricas urgentes.",
                            Nombre = "Reparación de cortocircuitos",
                            PrecioSugerido = 30000m,
                            RubroId = 1,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Armado, reemplazo y revisión de tableros eléctricos.",
                            Nombre = "Tableros y térmicas",
                            PrecioSugerido = 45000m,
                            RubroId = 1,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Atención rápida para cortes, riesgos o fallas críticas.",
                            Nombre = "Urgencia eléctrica 24h",
                            PrecioSugerido = 50000m,
                            RubroId = 1,
                            Unidad = "por urgencia"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Detección y arreglo de pérdidas visibles o internas.",
                            Nombre = "Reparación de pérdidas de agua",
                            PrecioSugerido = 30000m,
                            RubroId = 2,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Destapación de cañerías, piletas, baños y desagües.",
                            Nombre = "Destapaciones",
                            PrecioSugerido = 35000m,
                            RubroId = 2,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Colocación y reemplazo de griferías, flexibles y accesorios.",
                            Nombre = "Instalación de grifería",
                            PrecioSugerido = 25000m,
                            RubroId = 2,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Instalación, conexión y revisión de equipos de agua caliente.",
                            Nombre = "Termotanques y calefones",
                            PrecioSugerido = 55000m,
                            RubroId = 2,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Acompañamiento responsable para niños en domicilio.",
                            Nombre = "Cuidado de niños por hora",
                            PrecioSugerido = 5000m,
                            RubroId = 3,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Cuidado extendido con rutinas, comidas y acompañamiento.",
                            Nombre = "Niñera jornada completa",
                            PrecioSugerido = 30000m,
                            RubroId = 3,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Descripcion = "Acompañamiento en tareas y hábitos de estudio.",
                            Nombre = "Apoyo escolar inicial",
                            PrecioSugerido = 8000m,
                            RubroId = 3,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Descripcion = "Servicio ocasional en horarios nocturnos.",
                            Nombre = "Cuidado eventual nocturno",
                            PrecioSugerido = 12000m,
                            RubroId = 3,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Descripcion = "Acompañamiento básico de salud y bienestar en domicilio.",
                            Nombre = "Cuidado domiciliario",
                            PrecioSugerido = 12000m,
                            RubroId = 4,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Descripcion = "Toma de presión, temperatura y controles básicos.",
                            Nombre = "Control de signos vitales",
                            PrecioSugerido = 10000m,
                            RubroId = 4,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Descripcion = "Aplicación segura con indicación médica correspondiente.",
                            Nombre = "Aplicación de inyectables",
                            PrecioSugerido = 12000m,
                            RubroId = 4,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Descripcion = "Asistencia y seguimiento básico tras una intervención.",
                            Nombre = "Acompañamiento postoperatorio",
                            PrecioSugerido = 35000m,
                            RubroId = 4,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Descripcion = "Revisión inicial de fallas y presupuesto de reparación.",
                            Nombre = "Diagnóstico mecánico",
                            PrecioSugerido = 25000m,
                            RubroId = 5,
                            Unidad = "por diagnóstico"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Descripcion = "Cambio de aceite, filtros y revisión general.",
                            Nombre = "Service básico",
                            PrecioSugerido = 45000m,
                            RubroId = 5,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Descripcion = "Revisión y reparación de sistemas de freno y suspensión.",
                            Nombre = "Frenos y tren delantero",
                            PrecioSugerido = 65000m,
                            RubroId = 5,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Descripcion = "Asistencia móvil para fallas o emergencias vehiculares.",
                            Nombre = "Auxilio mecánico",
                            PrecioSugerido = 40000m,
                            RubroId = 5,
                            Unidad = "por salida"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Descripcion = "Trabajo de corte, plegado y preparación de piezas metálicas.",
                            Nombre = "Cortes y plegados",
                            PrecioSugerido = 40000m,
                            RubroId = 6,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Descripcion = "Fabricación y reparación de rejas, portones y estructuras.",
                            Nombre = "Rejas y estructuras",
                            PrecioSugerido = 90000m,
                            RubroId = 6,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Descripcion = "Reparaciones y ajustes en piezas o instalaciones metálicas.",
                            Nombre = "Mantenimiento metalúrgico",
                            PrecioSugerido = 50000m,
                            RubroId = 6,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Descripcion = "Asesoramiento y fabricación de piezas a medida.",
                            Nombre = "Diseño de piezas simples",
                            PrecioSugerido = 60000m,
                            RubroId = 6,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Descripcion = "Reparaciones de soldadura en hogares y comercios.",
                            Nombre = "Soldadura domiciliaria",
                            PrecioSugerido = 45000m,
                            RubroId = 7,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Descripcion = "Trabajos estructurales con evaluación técnica previa.",
                            Nombre = "Soldadura estructural",
                            PrecioSugerido = 90000m,
                            RubroId = 7,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            Descripcion = "Soldadura, refuerzo y ajuste de portones.",
                            Nombre = "Reparación de portones",
                            PrecioSugerido = 55000m,
                            RubroId = 7,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            Descripcion = "Reparación y fabricación de piezas de herrería simple.",
                            Nombre = "Herrería liviana",
                            PrecioSugerido = 50000m,
                            RubroId = 7,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            Descripcion = "Diagnóstico y reparación de equipos del hogar.",
                            Nombre = "Reparación de electrodomésticos",
                            PrecioSugerido = 30000m,
                            RubroId = 8,
                            Unidad = "por diagnóstico"
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            Descripcion = "Instalación, limpieza y mantenimiento de split.",
                            Nombre = "Aire acondicionado",
                            PrecioSugerido = 55000m,
                            RubroId = 8,
                            Unidad = "por equipo"
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            Descripcion = "Mantenimiento de heladeras, cámaras y freezers comerciales.",
                            Nombre = "Refrigeración comercial",
                            PrecioSugerido = 65000m,
                            RubroId = 8,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            Descripcion = "Reparaciones técnicas variadas para hogares y comercios.",
                            Nombre = "Soporte técnico general",
                            PrecioSugerido = 30000m,
                            RubroId = 8,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            Descripcion = "Reparación, limpieza, instalación y optimización de equipos.",
                            Nombre = "Soporte PC y notebook",
                            PrecioSugerido = 25000m,
                            RubroId = 9,
                            Unidad = "por equipo"
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            Descripcion = "Instalación y mejora de redes hogareñas o comerciales.",
                            Nombre = "Redes y WiFi",
                            PrecioSugerido = 35000m,
                            RubroId = 9,
                            Unidad = "por trabajo"
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            Descripcion = "Landing pages, formularios y sitios institucionales.",
                            Nombre = "Desarrollo web simple",
                            PrecioSugerido = 120000m,
                            RubroId = 9,
                            Unidad = "por proyecto"
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            Descripcion = "Asistencia digital a distancia para problemas de software.",
                            Nombre = "Soporte remoto",
                            PrecioSugerido = 12000m,
                            RubroId = 9,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            Descripcion = "Acompañamiento no médico para adultos mayores.",
                            Nombre = "Cuidador de adultos",
                            PrecioSugerido = 9000m,
                            RubroId = 10,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 38,
                            Activo = true,
                            Descripcion = "Acompañamiento especializado según necesidad del paciente.",
                            Nombre = "Acompañante terapéutico",
                            PrecioSugerido = 12000m,
                            RubroId = 10,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 39,
                            Activo = true,
                            Descripcion = "Ayuda en traslados, rutinas y acompañamiento diario.",
                            Nombre = "Asistencia para movilidad",
                            PrecioSugerido = 10000m,
                            RubroId = 10,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            Descripcion = "Acompañamiento nocturno para pacientes o adultos mayores.",
                            Nombre = "Cuidado nocturno",
                            PrecioSugerido = 35000m,
                            RubroId = 10,
                            Unidad = "por noche"
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            Descripcion = "Personal para tareas productivas, planta o línea.",
                            Nombre = "Operario de producción",
                            PrecioSugerido = 25000m,
                            RubroId = 11,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            Descripcion = "Tareas de empaque, clasificación y preparación de pedidos.",
                            Nombre = "Armado y embalaje",
                            PrecioSugerido = 22000m,
                            RubroId = 11,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            Descripcion = "Revisión visual, clasificación y control básico de productos.",
                            Nombre = "Control de calidad",
                            PrecioSugerido = 28000m,
                            RubroId = 11,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 44,
                            Activo = true,
                            Descripcion = "Tareas preventivas y correctivas en entornos productivos.",
                            Nombre = "Mantenimiento de planta",
                            PrecioSugerido = 45000m,
                            RubroId = 11,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 45,
                            Activo = true,
                            Descripcion = "Atención comercial, ventas y promociones por jornada.",
                            Nombre = "Vendedor/a eventual",
                            PrecioSugerido = 25000m,
                            RubroId = 12,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 46,
                            Activo = true,
                            Descripcion = "Entrega de productos, paquetes o documentación.",
                            Nombre = "Reparto urbano",
                            PrecioSugerido = 18000m,
                            RubroId = 12,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 47,
                            Activo = true,
                            Descripcion = "Soporte presencial o remoto para comercios y servicios.",
                            Nombre = "Atención al cliente",
                            PrecioSugerido = 22000m,
                            RubroId = 12,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 48,
                            Activo = true,
                            Descripcion = "Tareas logísticas, depósito y movimiento de mercadería.",
                            Nombre = "Carga y descarga",
                            PrecioSugerido = 28000m,
                            RubroId = 12,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 49,
                            Activo = true,
                            Descripcion = "Carga de datos, gestión documental y apoyo administrativo.",
                            Nombre = "Administración freelance",
                            PrecioSugerido = 15000m,
                            RubroId = 13,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            Descripcion = "Emisión, seguimiento y organización de facturas/cobros.",
                            Nombre = "Facturación y cobranzas",
                            PrecioSugerido = 18000m,
                            RubroId = 13,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            Descripcion = "Soporte contable básico y ordenamiento de comprobantes.",
                            Nombre = "Asistente contable",
                            PrecioSugerido = 20000m,
                            RubroId = 13,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            Descripcion = "Ordenamiento de gastos, ingresos y reportes simples.",
                            Nombre = "Organización financiera",
                            PrecioSugerido = 25000m,
                            RubroId = 13,
                            Unidad = "por hora"
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            Descripcion = "Atención de mesas para eventos, bares o restaurantes.",
                            Nombre = "Mozo/a eventual",
                            PrecioSugerido = 25000m,
                            RubroId = 14,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            Descripcion = "Preparación, asistencia y orden en cocina.",
                            Nombre = "Ayudante de cocina",
                            PrecioSugerido = 28000m,
                            RubroId = 14,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 55,
                            Activo = true,
                            Descripcion = "Atención de huéspedes, check-in y soporte operativo.",
                            Nombre = "Recepción hotelera",
                            PrecioSugerido = 30000m,
                            RubroId = 14,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 56,
                            Activo = true,
                            Descripcion = "Servicio gastronómico para reuniones y eventos.",
                            Nombre = "Catering para eventos",
                            PrecioSugerido = 90000m,
                            RubroId = 14,
                            Unidad = "por evento"
                        },
                        new
                        {
                            Id = 57,
                            Activo = true,
                            Descripcion = "Reparaciones, ampliaciones y trabajos de obra menor.",
                            Nombre = "Albañilería general",
                            PrecioSugerido = 50000m,
                            RubroId = 15,
                            Unidad = "por jornada"
                        },
                        new
                        {
                            Id = 58,
                            Activo = true,
                            Descripcion = "Preparación y pintura de ambientes interiores.",
                            Nombre = "Pintura de interiores",
                            PrecioSugerido = 65000m,
                            RubroId = 15,
                            Unidad = "por ambiente"
                        },
                        new
                        {
                            Id = 59,
                            Activo = true,
                            Descripcion = "Tareas generales de mantenimiento domiciliario o comercial.",
                            Nombre = "Mantenimiento integral",
                            PrecioSugerido = 45000m,
                            RubroId = 15,
                            Unidad = "por visita"
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            Descripcion = "Equipo coordinado para trabajos de construcción y mantenimiento.",
                            Nombre = "Cuadrilla de obra",
                            PrecioSugerido = 180000m,
                            RubroId = 15,
                            Unidad = "por jornada"
                        });
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SesionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Exito")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("MotivoCierre")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesUsuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalificacionCliente")
                        .HasColumnType("integer");

                    b.Property<int?>("CalificacionProfesional")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ComentarioCliente")
                        .HasColumnType("text");

                    b.Property<string>("ComentarioProfesional")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostoTraslado")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DistanciaKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRequerida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Incentivo")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<decimal>("PresupuestoEstimado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PresupuestoFinal")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("ServicioId");

                    b.ToTable("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecibeNotificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VerificadoRenaper")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProfesionalRubro", b =>
                {
                    b.Property<int>("ProfesionalesId")
                        .HasColumnType("integer");

                    b.Property<int>("RubrosProfesionalesId")
                        .HasColumnType("integer");

                    b.HasKey("ProfesionalesId", "RubrosProfesionalesId");

                    b.HasIndex("RubrosProfesionalesId");

                    b.ToTable("ProfesionalRubro");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.AuditoriaEvento", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany("AuditoriaEventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Certificado", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Profesional", "Profesional")
                        .WithMany("Certificados")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("AppServicios.Api.Domain.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Direccion", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.MensajeSolicitud", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.SolicitudTrabajo", "SolicitudTrabajo")
                        .WithMany("Mensajes")
                        .HasForeignKey("SolicitudTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SolicitudTrabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Notificacion", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.PagoProfesional", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("AppServicios.Api.Domain.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.PushSubscription", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Rubro", "Rubro")
                        .WithMany("Servicios")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SesionUsuario", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany("SesionesUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Cliente", "Cliente")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Profesional", "Profesional")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppServicios.Api.Domain.Servicio", "Servicio")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ProfesionalRubro", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Profesional", null)
                        .WithMany()
                        .HasForeignKey("ProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Rubro", null)
                        .WithMany()
                        .HasForeignKey("RubrosProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Rubro", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Usuario", b =>
                {
                    b.Navigation("AuditoriaEventos");

                    b.Navigation("Cliente");

                    b.Navigation("Notificaciones");

                    b.Navigation("Profesional");

                    b.Navigation("SesionesUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
